# Generated by Django 3.0 on 2020-01-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_shool', models.CharField(max_length=100)),
                ('higher_education', models.CharField(max_length=100)),
                ('level_of_education', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('other_certificates', models.CharField(max_length=100)),
            ],
        ),
    ]
