# Generated by Django 3.0.3 on 2020-02-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
